### ISSUE TITLE
RouteConverter for Android

### ISSUE THREAD

**Issue by hilandae** [cpesch/RouteConverter#39]
Hello, your program is very helpful but i need an android version. I have tried to run it with Java Manager-Emulate Java on  https://play.google.com/store/apps/details?id=com.java.manager but without success. Also can you add Sygic itf format.
Best Regards

**Comment by cpesch** [comment]
RouteConverter won't run on a tablet: it uses APIs only available in the JDK. And I guess it would not make fun to use it on a touch devices since it was developed for point and click devices, i.e. buttons are too small, drag and drop is not available on tablets, the whole UX doesn't fit.
