### ISSUE TITLE
Zoom reset after position delete

### ISSUE THREAD

**Issue by jareware** [cpesch/RouteConverter#41]
Thanks for a great piece of software!

Whenever I delete a position from the position list, the next position I click on resets the zoom level to very far away. This makes it kind of hard to do clean-up where you need to manually remove points from here and there.

Any idea what could cause this?

**Comment by cpesch** [comment]
It's actually a very tiny patch with a big effect:
https://github.com/cpesch/RouteConverter/commit/e520e9f7f70ec9b3c095d9d5154f9d22c2512106

Please try the latest prerelease or sync to HEAD to get rid of the problem.

**Comment by jareware** [comment]
This seems to work very nicely, thank you!
