### ISSUE TITLE
Umlaut broken

### ISSUE THREAD

**Issue by emdete** [cpesch/RouteConverter#42]
The German Texts Länge, Höhe and Gefälle are not shown correctly, the umlaut is shown as questionmark.

**Comment by cpesch** [comment]
That was an issue with the 2.16. Please try the 2.16.1 or the latest prerelease.

**Comment by emdete** [comment]
it is the current prerelease from today.

**Comment by cpesch** [comment]
Not here...I'm using "RouteConverter Online Edition 2.17-SNAPSHOT-576 vom 8. September 2015"

![umlauts](https://cloud.githubusercontent.com/assets/40717/9748354/68e7e544-5684-11e5-9214-1ae4122cc67a.png)

**Comment by emdete** [comment]
![rc](https://cloud.githubusercontent.com/assets/3251523/9758614/01fdf170-56e8-11e5-8346-3ba21e28d8e1.png)

gotten from http://www.routeconverter.com/prereleases/en (link is http://static.routeconverter.com/download/RouteConverterPrereleaseLinuxOffline.jar).

**Comment by emdete** [comment]
ah, ok, just downloaded today and here it's fixed..... thank you! :D

**Comment by cpesch** [comment]
Thank you for reporting :-)
