### ISSUE TITLE
Can't select from position list

### ISSUE THREAD

**Issue by jareware** [cpesch/RouteConverter#43]
I'm having this strange issue where after a short while of use I can't select positions from the position list anymore. Please the [screen recording](http://s3.jrw.fi.s3.amazonaws.com/routeconverter-issue-43.mov) and [logfile](http://s3.jrw.fi/routeconverter-issue-43.log).

This happens with both the most recent stable and pre-release. Also, I'm pretty sure I've used the exact same version on another machine (which I physically cannot access right now) and it's worked fine.

```
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by cpesch** [comment]
Hi jareware,

that's indeed strange. Please start RouteConverter from the console (the FAQ describes how) and send me the output of the console. I'm expecting exceptions with stack trace that might help to track down the problems.

Kind regards
Christian

**Comment by jareware** [comment]
```
$ java -jar Downloads/RouteConverterPrereleaseMac.jar
Sep 15, 2015 3:57:26 AM slash.navigation.gui.Application invokeNativeInterfaceMethod
INFO: Cannot invoke NativeInterface#open(): java.lang.reflect.InvocationTargetException
Sep 15, 2015 3:57:26 AM slash.navigation.gui.Application invokeNativeInterfaceMethod
INFO: Cannot invoke NativeInterface#runEventPump(): java.lang.reflect.InvocationTargetException
Logging to /var/folders/hq/gfw6_nr17lngh72f4ld99m7h0000gp/T/RouteConverter.log
```

All of these are startup messages though, and I don't get anything more during runtime, before or after the waypoint list stops processing the clicks. :/

**Comment by jareware** [comment]
Right, this is even more odd; I downgraded to Java `1.7.0_79`, and I'm not seeing the issue, **but** when I open the app I can only see the position list and the profile, not the map panel, it stays hidden no matter what I do. Again, happens both on the latest stable & prerelease.

**Comment by jareware** [comment]
I'm currently working around this by using RouteConverter in a Windows virtual machine, works well enough... ;)

**Comment by cpesch** [comment]
After the startup messages everything is logged to /var/folders/hq/gfw6_nr17lngh72f4ld99m7h0000gp/T/RouteConverter.log
as the message says 

    Logging to /var/folders/hq/gfw6_nr17lngh72f4ld99m7h0000gp/T/RouteConverter.log

If there are exceptions, you should see them there
