### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by boldtrn** [cpesch/RouteConverter#44]
Hi,

I was wondering if it would be possible to include RouteConverter in my project using Maven? I could not find it in the common repositories.

Best,
Robin

**Comment by cpesch** [comment]
Hi Robin,

of course you can include it - note it's GPL-licensed.

Since there was no demand so far I'm just uploading the binaries to my download server.

What are you planning to use?

Kind regards
Christian

**Comment by boldtrn** [comment]
Hi Christian,

currently I am working on a route planer. I want to convert gpx files to all common formats. And maybe, not sure if RouteConverter supports it, create intermediate waypoints from a given gpx track.

Mhm I guess GPL shouldn't be a problem. I do not provide provide my source code as open-source, but create a web-service. I think this should be fine with the GPL?

It would be great, if you could include RouteConverter in a public maven repository.

Best,
Robin

**Comment by cpesch** [comment]
Hi Robin,

this is fine for the GPL - although it would be nice if you give enhancements back.

For now, you have two options:
- use the ready-to-go RouteConverterCmdLine.jar
- checkout the code and compile yourself 

Kind regards
Christian

**Comment by boldtrn** [comment]
Hi Christian,

thanks. Usually I am reporting issues and try to fix the myself if I am able to.

It would be great if you could consider adding your releases for example here: http://central.sonatype.org/pages/ossrh-guide.html

From my point of view this will also increase usage of RouteConverter in 3rd party applications. I cannot use RouteConverter as a .jar because my whole build process relies on maven, therefore I had to create a private release of RouteConverter and register that.

Best,
Robin

**Comment by cpesch** [comment]
Hi Robin,

which artifacts are you using?

Kind regards
Christian

**Comment by boldtrn** [comment]
Hi Christian,

I think that I only need the Conversion of different formats (gpx, itn, txt ...), which should be included in the CommandLine package?

If there are more nuggets that would help me, I'd love to use them as well. For example creating intermediate Waypoints when converting a track to a waypoint based file.

Best,
Robin
