### ISSUE TITLE
test cases in navigation-formats/ fail

### ISSUE THREAD

**Issue by ufux** [cpesch/RouteConverter#49]
Reason is that some test data is not checked in in the directory innavigation-formats-samples/ 
e.g. file "from-mgintra09.bcr", which is used in testcase

RouteConverter/navigation-formats/src/test/java/slash/navigation/bcr/BcrReadWriteRoundtripIT.java

**Comment by cpesch** [comment]
Actually most integration tests fail... since the test files I've accumulated over the years contain personal data, I cannot publish them.
