### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by xmha97** [cpesch/RouteConverter#56]
Hello,
I would like to use the RouteConverter on a USB stick.
Is it possible to create a Portable version of this application?
I used this command:
`javaw.exe -jar RouteConverter.jar -portableFolder .\data`
But data saved in `%appdata%` not `.\data`

**Comment by cpesch** [comment]
There was a discussion in the forum a while ago: https://forum.routeconverter.com/thread-2224.html
Please have a look at it and decide how to contribute.

**Comment by amirrammari** [comment]
Hello @cpesch 
-portableFolder parameter not working
please help me

**Comment by cpesch** [comment]
That parameter never existed. Please read my comment above

**Comment by cpesch** [comment]
please try Portable Apps prerelease on
https://www.routeconverter.com/prereleases/en

**Comment by xmha97** [comment]
Thank you.
It is suggested to contact PortableApps.com and put the RouteConverter app on their site.
https://portableapps.com/about/contact
https://portableapps.com/apps

**Comment by cpesch** [comment]
That's my plan for later this year, when I have some positive reports that it works for users out there.
