### ISSUE TITLE
Please add this app to Chocolatey

### ISSUE THREAD

**Issue by xmha97** [cpesch/RouteConverter#57]
Hello
Chocolatey is a package manager for Windows. (like apt-get on Linux)
Please add RouteConverter app to Chocolatey

For more information see below document:
How to create your own packages on Chocolatey

Thanks.

**Comment by cpesch** [comment]
Did you mean https://chocolatey.org/blog/create-chocolatey-packages ?

**Comment by amirrammari** [comment]
> Did you mean https://chocolatey.org/blog/create-chocolatey-packages ?

Sorry, Yes.

**Comment by cpesch** [comment]
Why don't you try it?

**Comment by amirrammari** [comment]
> Why don't you try it?

Now I using RouteConverter.

but I want to install it on my computer and see the app icon on the start menu because I use your app a lot.

**Comment by cpesch** [comment]
I don't see the need to create an installer for an app which I've tried to make portable (not yet portable enough as you can see in issue https://github.com/cpesch/RouteConverter/issues/56)
 
There are easy ways to accomplish your tasks:

- https://www.windowscentral.com/add-app-shortcuts-start-menu-manually-windows-10
- https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477

**Comment by cpesch** [comment]
There is a beta version for RouteConverter as a portable app: https://portableapps.com/node/65169

Since Chocolatey is an even smaller nice that Portable Apps for RouteConverter, I won't follow up on it for now. Feel free to experiment and share code if you make steps with Chocolatey.

**Comment by xmha97** [comment]
> 

Thanks.
