### ISSUE TITLE
Shift start time of a track

### ISSUE THREAD

**Issue by tibtof** [cpesch/RouteConverter#65]
I'm trying to use _RouteConverter_ to sync `.gpx` and video files. There are some gaps in the video file and I want to remove those time intervals from the `.gpx`. For this, I need to change the start time of a track and shift all the position time stamps with the corresponding offset.
The workflow is described in [this article](https://support.kinomap.com/hc/en-us/articles/360044825591-How-to-manage-when-you-took-a-pause-during-your-video-recording-):

> 1. Load GPS track from your ride.
> 2. Localize and mark the break in your GPS track - the track is split into two segments - each one different color on the map.
> 3. You can use the auto-discovery tool for gaps longer than 1 min. 
> 4. Save the newly created segment - a new track will show up in the left panel.
> 5. Change the time of the first track point in the new track (for example if the gap cut out from the video is 20 seconds long, you have to subtract 20 s from the original time).
> 6. Delete the second segment from the first track and merge both tracks. Save to a new file and it's ready.

I didn't find a way to use _RouteConverter_ for step 5. Is it possible?

**Comment by cpesch** [comment]
Dear @tibtof,

not precisely, but... it's possible to change the time of the first and last position by 20 seconds, then select all positions and call Complete->Time. This distributes the time interval between the first and the last position over all positions depending on their distance. I guess not exactly, what you want although it might work if there positions are closely together.
If this is not, what you were searching for: feel free to take the code and experiment. PositionAugmenter#processTimes is a good starting point to solve your problem and maybe create a PR if it's suitable for everyone.
