### ISSUE TITLE
Adding waypoints within/around the marker not working correctly under Linux

### ISSUE THREAD

**Issue by ds10git** [cpesch/RouteConverter#67]
I've been using RouteConverter for years under Ubuntu, thanks it really is great but one issue has always annoyed me. Whenever I need to add a new waypoint within/around the marker, it's just not working correctly. Sometimes the new point is added way off from the mouse pointer, another time the marker is selected for moving it around and another time the new point is added at the position of the point the marker is on even if the mouse is at another place.

So I've finally looked into the source code and added to ignore marker handling whenever CTRL is down in `slash.navigation.mapview.mapsforge.helpers.MapViewMoverAndZoomer`, because CTRL is typically down when a new waypoint should be added.

```    
private MarkerAndDelta getMarkerFor(MouseEvent e) {
	if((e.getModifiersEx() & KeyEvent.CTRL_DOWN_MASK) != KeyEvent.CTRL_DOWN_MASK) {
		LatLong tapLatLong = projection.fromPixels(e.getX(), e.getY());
		org.mapsforge.core.model.Point tapXY = new org.mapsforge.core.model.Point(e.getX(), e.getY());
	
		Layers layers = layerManager.getLayers();
		for (int i = layers.size() - 1; i >= 0; --i) {
			Layer layer = layers.get(i);
			if (!(layer instanceof Marker))
				continue;
	
			org.mapsforge.core.model.Point layerXY = projection.toPixels(layer.getPosition());
			if (layer.onTap(tapLatLong, layerXY, tapXY)) {
				return new MarkerAndDelta((DraggableMarker) layer, layerXY.x - tapXY.x, layerXY.y - tapXY.y);
			}
		}
	}
	return null;
}
```

It's working as expected, with that change a new waypoint can be added without any issues in and around the marker.

**Comment by cpesch** [comment]
@ds10git I've removed the shadow from the marker in the latest prerelease after some discussions in the forum https://forum.routeconverter.com/thread-3610.html

Did you try the latest prerelease?

**Comment by ds10git** [comment]
I didn't tried the prerelase but the HEAD revision instead and it had the same issue as always and it's happening on all my devices, one runs Unity the other Mate. As long as I used RouteConverter that was always a problem, so I had to add a new waypoint further away from the marker and then move it to the wanted position. That worked but it's rather time consuming for narrow ways with many turns especially for hiking trails.

I've recorded two videos to demonstrate (the marker is semi transparent since I've changed the SVG image to be not fully opaque).

First without ignoring CTRL: [http://download.tvbrowser.org/plugins/routeconverter-without-ignore-ctrl.mkv](url)
As you can see, whenever the mouse pointer is pointing around the marker CTRL+Left Click leads to a new waypoint being added at the same location the marker is pointing at, even though the mouse is pointing at a different location. The jumping of the new waypoint to another location is hard to reproduce but it happens occasionally, here in the video it did not happen. Further it's completely impossible to add a new waypoint at a location inside the marker image.

Second with ignoring CTRL: [http://download.tvbrowser.org/plugins/routeconverter-with-ignore-ctrl.mkv](url)
Here each CTRL+Left Click adds a new waypoint exactly at the location the mouse pointer is pointing at.
(The semi transparent marker makes it even easier to add a new waypoint inside the marker.)

**Comment by cpesch** [comment]
Thank you for point this out. Please try the latest prerelease which I've just uploaded.

**Comment by ds10git** [comment]
Thanks, works great now.
