### ISSUE TITLE
Hidden option for look and feel

### ISSUE THREAD

**Issue by ds10git** [cpesch/RouteConverter#74]
I had the problem under Ubuntu Mate that the GTK look and feel was not used by RC instead it fell back to Metal. When I tried to add the hidden preference for the look and feel it didn't work. Only after searching the source code for the preference I got it to work. The hidden preference in HiddenRouteConverterOptions.reg is pointing to `[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\slash\navigation\gui]`
but the preference only worked with using 
`[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\slash\navigation\gui\helpers]`

IMHO this shouldn't even be a hidden preference. I searched a really long time to find this preference and every person familiar with Java applications will expect to find an option to select the look and feel via the GUI.

**Comment by cpesch** [comment]
Thank you, I've fixed
https://static.routeconverter.com/download/HiddenRouteConverterOptions.reg

Actually I've introduced the hidden options to avoid creating a huge preferences dialog where you need explanations of the options. It's already too large and leads to lots of questions.
