### ISSUE TITLE
Is it possible to set the width of tracks?

### ISSUE THREAD

**Issue by stefanrueger** [cpesch/RouteConverter#75]
Didn't find an obvious option in the menus. Thank you.

BTW. The README.md instruction
```
git clone git://github.com/cpesch/RouteConverter.git
```
timed out for me. I had to 
```
git clone git@github.com:cpesch/RouteConverter.git
```

**Comment by cpesch** [comment]
There is no menu option. Please use the hidden options
https://static.routeconverter.com/download/HiddenRouteConverterOptions.reg

```
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\slash\navigation\mapview\mapsforge]
"track/Line/Width"="2"
"route/Line/Width"="5
```

**Comment by stefanrueger** [comment]
Thanks. Linux here, so cannot even begin to parse your tip. However,
```
$ find ~ -ipath \*Prefs/slash/navigation/mapview/mapsforge\* -type f
~/.java/.userPrefs/slash/navigation/mapview/mapsforge/prefs.xml
```
uncovers an options file with the following contents
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="centerLatitude" value="51.476852"/>
  <entry key="centerLongitude" value="-0.000500"/>
  <entry key="centerZoom" value="15"/>
</map>
```
Now what?

**Comment by stefanrueger** [comment]
However, I created a solution outside RouteConverter: the following Imagemagick command lines let you copy a map screenshot `input.png` to `output.png` whilst dilating the blue (#0033ff) path.
```
convert input.png -fill \#000000 +opaque \#0033ff -fill \#ffffff -opaque \#0033ff -morphology Dilate Octagon -transparent \#000000 -fill \#0033ff -opaque \#ffffff tmp.png
convert -composite -gravity center input.png tmp.png output.png
rm tmp.png
```
Changes

![input](https://user-images.githubusercontent.com/14282046/179202864-337402cc-de34-4935-9e38-b021e6a38683.png)

to

![output](https://user-images.githubusercontent.com/14282046/179202966-2edab3ab-7973-44fd-9da9-3abcd3b0485a.png)

**Comment by cpesch** [comment]
> Now what?

Now Analogieschluß:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="trackLineWidth" value="2"/>
  <entry key="routeLineWidth" value="5"/>
</map>
```

**Comment by stefanrueger** [comment]
> `<entry key="trackLineWidth" value="2"/>`

Thanks, adding that in `~/.java/.userPrefs/slash/navigation/mapview/mapsforge/prefs.xml` works like a charm in Linux
