### ISSUE TITLE
JRC RTM FILES

### ISSUE THREAD

**Issue by YuryKomar** [cpesch/RouteConverter#77]
Hi.
Does your Route Converter converts to RTM format of JRC ECDIS?

I am looking for a code to do so.
I am able to read .rtm routes, but writing is terrinbe, it should have some checksum at the end of file, but I have no idea how to generate this checksum.

looking for your help.
If you you does not have rtm support yet, I cam give you what I found and use to load rtm files I'm my app: ECDIS Route Manager
http://sea-soft.ru

**Comment by cpesch** [comment]
Hi Yury,

RouteConverter does not support the RTM format of JRC ECDIS – and so far nobody asked for it.
The only source about the format which I've found is here: https://www.cruisersforum.com/forums/f134/route-in-format-rtm-260422.html

Best regards
Christian

**Comment by YuryKomar** [comment]
Hi, thanks for reply.
I have managed to read the route, but to save it, looks like, require some checksum at the end of file, 4 bytes (maybe CRC32), but what data used to compute it, I don't know.
Cannot find it.
--
Best Regards,
Yury Komar понедельник, 19 сентября 2022г., 16:39 +10:00 от Christian Pesch  ***@***.*** :
