### ISSUE TITLE
Routeconverter wont start on Java 17

### ISSUE THREAD

**Issue by telemaxx** [cpesch/RouteConverter#78]
Hi together:

![grafik](https://user-images.githubusercontent.com/22706487/206842666-62735d29-947d-48de-bb7a-869d2ed5b85c.png)

Is it planed to support java 17?

Thanks,
Thomas

**Comment by cpesch** [comment]
Hi Thomas,

yes. Currently still more than 40% of the users use Java 8. If this drops below 5% its time to start with Java 17 support – which means losing Java 8 support. 

Best regards
Christian

**Comment by telemaxx** [comment]
Hi Christian,
thank you for youre reply.

today i had a java torture.

At the beginning i had a working java11 and eclipse 2022-09

Than i tried to update to eclipse 2022-12, which wont work without java17

with java 17 i could update eclipse, but many other thinks did not work anymore.

now i downgraded to java11 an eclipse 2022-09. (Was also not easy)
but now anything is running again, also my loved routeconverter.

"don't touch a running system" is sometimes the best.


Best wishes,
Thomas
