### ISSUE TITLE
<type> tag not supported

### ISSUE THREAD

**Issue by heX16** [cpesch/RouteConverter#83]
I upload my wapoints list, it uses a tag `<type>`.
After saving, this tag disappears.
This tag is in the [standard ](https://www.topografix.com/GPX/1/1/#type_wptType)- it would be good if it would not be lost when saving.

Example:

```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd~ 4.4.7" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>favorites</name>
    <time>2023-09-27T16:20:32Z</time>
  </metadata>
  <wpt lat="45.2532852" lon="19.8611541">
    <ele>87.5</ele>
    <time>2023-07-07T22:19:18Z</time>
    <name>just name</name>
    <type>TYPE</type>
  </wpt> 
</gpx>   
```

**Comment by cpesch** [comment]
I've copied your example into a file, opened it and saved it again: <type>TYPE</type> is still present.

Actually, there is dedicated code to preserve the read data:
https://github.com/cpesch/RouteConverter/blob/51d03e36d549bb8890abd48e6edd1f10b1385205/navigation-formats/src/main/java/slash/navigation/gpx/Gpx11Format.java#L252

Please explain why you claim the <type> is lost!
